#!/bin/bash
# Automated Render.com & MongoDB Atlas Deployment Script
# For Israeli 2026 Elections Survey

set -e

echo "🚀 Israeli 2026 Elections Survey - Automated Deployment Script"
echo "=============================================================="
echo ""

# Configuration
GITHUB_USER="yakovganam"
REPO_NAME="israeli-2026-elections-survey"
GITHUB_REPO_URL="https://github.com/${GITHUB_USER}/${REPO_NAME}"
RENDER_APP_NAME="israeli-2026-elections"

echo "📋 Pre-flight checks..."
echo "  ✅ GitHub Repository: $GITHUB_REPO_URL"
echo "  ✅ Code branch: master"
echo ""

echo "⚠️  MANUAL STEPS REQUIRED:"
echo ""
echo "1️⃣  SET UP MONGODB ATLAS"
echo "   Step 1.1: Go to https://www.mongodb.com/cloud/atlas"
echo "   Step 1.2: Sign up / Log in"
echo "   Step 1.3: Create new project → 'Israeli Elections Survey'"
echo "   Step 1.4: Create free cluster (M0):"
echo "            - Name: cluster0"
echo "            - Region: Select your region"
echo "   Step 1.5: Go to 'Database Access' → 'Add Database User'"
echo "            - Username: survey_user"
echo "            - Password: [Generate and save securely]"
echo "            - Role: Atlas Admin"
echo "   Step 1.6: Go to 'Network Access' → 'Add IP Address'"
echo "            - IP: 0.0.0.0/0 (allow everywhere)"
echo "            - Click confirm"
echo "   Step 1.7: Click 'Clusters' → 'Connect' → 'Connect your app'"
echo "            - Driver: Node.js 4.0 or later"
echo "            - Copy connection string"
echo "            - Replace <password> with your password"
echo ""
echo "   💾 SAVE THIS CONNECTION STRING:"
echo "   mongodb+srv://survey_user:YOUR_PASSWORD@cluster0.mongodb.net/surveydb?retryWrites=true&w=majority"
echo ""

echo "2️⃣  CREATE RENDER WEB SERVICE"
echo "   Step 2.1: Go to https://render.com"
echo "   Step 2.2: Sign up / Log in (GitHub recommended)"
echo "   Step 2.3: Click 'New +' → 'Web Service'"
echo "   Step 2.4: Select repository:"
echo "            - Repo: $GITHUB_REPO_URL"
echo "            - Branch: master"
echo "   Step 2.5: Configure service:"
echo "            - Name: $RENDER_APP_NAME"
echo "            - Environment: Node"
echo "            - Build Command: npm install"
echo "            - Start Command: npm start"
echo "            - Plan: Free"
echo ""

echo "3️⃣  SET ENVIRONMENT VARIABLES ON RENDER"
echo "   In Render Dashboard → Your Service → Environment:"
echo ""
echo "   Add these variables:"
echo "   NODE_ENV=production"
echo "   PORT=3000"
echo "   MONGODB_URI=mongodb+srv://survey_user:YOUR_PASSWORD@cluster0.mongodb.net/surveydb?retryWrites=true&w=majority"
echo ""

echo "4️⃣  DEPLOY"
echo "   - Click 'Create Web Service' button"
echo "   - Wait for build to complete (~3-5 minutes)"
echo "   - Get your live URL: https://$RENDER_APP_NAME.onrender.com"
echo ""

echo "5️⃣  VERIFY DEPLOYMENT"
echo "   Test these URLs:"
echo "   - Health check: https://$RENDER_APP_NAME.onrender.com/api/health"
echo "   - Survey page: https://$RENDER_APP_NAME.onrender.com/"
echo "   - Test voting functionality"
echo ""

echo "✅ DEPLOYMENT CHECKLIST"
echo "   [ ] MongoDB Atlas cluster created"
echo "   [ ] Database user created (survey_user)"
echo "   [ ] Network access configured"
echo "   [ ] Connection string copied"
echo "   [ ] Render.com account created"
echo "   [ ] GitHub repo connected to Render"
echo "   [ ] Environment variables set"
echo "   [ ] Web service deployed"
echo "   [ ] Homepage loads successfully"
echo "   [ ] Can vote for a party"
echo "   [ ] Results display correctly"
echo "   [ ] 24-hour vote cooldown works"
echo ""

echo "🔗 FINAL LINKS"
echo "   GitHub: $GITHUB_REPO_URL"
echo "   Live URL: https://$RENDER_APP_NAME.onrender.com"
echo "   Render Dashboard: https://dashboard.render.com"
echo "   MongoDB Atlas: https://cloud.mongodb.com"
echo ""

echo "📞 TROUBLESHOOTING"
echo "   Issue: Build fails"
echo "   → Check Render logs for npm install errors"
echo ""
echo "   Issue: MongoDB connection error"
echo "   → Verify MONGODB_URI env variable is correct"
echo "   → Check MongoDB cluster is running"
echo "   → Confirm network access allows 0.0.0.0/0"
echo ""
echo "   Issue: Voting not working"
echo "   → Check /api/health endpoint returns connected"
echo "   → Verify MONGODB_URI in Render environment"
echo ""

echo "=============================================================="
echo "Created: 2026-01-30"
echo "Ready for production deployment ✅"
